#!/bin/sh -e

#
# po/bluehoodtext, based on src/gdb/po/gdbtext from gdb
#

if test $# -lt 3
then
    echo "Usage: $0 <xgettext> <package>  <directory> ..." 1>&2
    exit 0
fi

xgettext=$1 ; shift
package=$1 ; shift

for d in "$@"
do
  __directories="$__directories --directory=$d"
done

for d in "$@"
do
  (
      cd $d
      find * \
	  -name '*-stub.c' -prune -o \
	  -name 'testsuite' -prune -o \
	  -name 'init.c' -prune -o \
	  -name '*.php' -print
  )
done | ${xgettext} \
    --default-domain=${package} \
    --copyright-holder="BlueHood Development Team" \
    --add-comments \
    --files-from=- \
    --force-po \
    --debug \
    --language=PHP \
    --keyword=_ \
    --keyword=N_ \
    --extract-all \
    --indent \
    --properties-output \
    --stringtable-output \
    --itstool \
    --foreign-user \
    ${__directories} \
    -o po/${package}.pot

